steps:
- id: "build image"
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', 
          '-t', 
          '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', 
          '.',
          "--build-arg",
          "_SETTINGS_MODULE=$_SETTINGS_MODULE",
        ]

- id: "push image"
  name: "gcr.io/cloud-builders/docker"
  args: ["push", '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}']

- id: "apply migrations"
  name: "gcr.io/google-appengine/exec-wrapper"
  args:
    [
      "-i",
      "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}",
      "-s",
      "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
      "-e",
      "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
      "--",
      "python",
      "manage.py",
      "migrate",
      "--settings",
      "config.env.prod",
    ]
- id: "collect static"
  name: "gcr.io/google-appengine/exec-wrapper"
  args:
    [
      "-i",
      "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}",
      "-s",
      "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
      "-e",
      "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
      "--",
      "python",
      "manage.py",
      "collectstatic",
      "--settings",
      "config.env.prod",
      "--verbosity",
      "2",
      "--noinput",
    ]
substitutions:
  _REGION: asia-northeast1
  _LOCATION: asia-northeast1
  _REPOSITORY: myrepo
  _IMAGE: djst_django
  _INSTANCE_NAME:  dockertest
  _SECRET_SETTINGS_NAME: secret
  _SETTINGS_MODULE: config.env.prod

images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'

